version: '3'
name: uptimekuma

services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    volumes:
      - updatekuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homelab
    ports:
      - 3001:3001
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.entrypoints=http"
      - "traefik.http.routers.uptimekuma.rule=Host(`uptimekuma.localhost`)"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
networks:
  homelab:
    external: true

volumes:
  updatekuma-data: