# Install in the container the chromium executable
# docker exec -it uptimekuma bash
# apt-get update
# apt-get install -y chromium
# exit
# Go to admin panel Settings/Docker Hosts and test the connection
# add monitor type Docker Container

version: '3'
name: traefik

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80       # Reverse proxy
      - 8080:8080   # Dashboard GUI
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homelab
    restart: unless-stopped

networks:
  homelab:
    external: true