global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: :80

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
