version: '3'
name: jenkins

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.entrypoints=http"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.localhost`)"

volumes:
  jenkins_home:

networks:
  homelab:
    external: true